---
- name: Remove zypper cache
  command: rm -rf /var/cache/zypper/*
  tags: zypper

- name: Clean zypper data
  command: zypper clean
  tags: zypper

- name: Install JDKs
  zypper: name={{item}} state=latest
  with_items:
    - java-1_8_0-openjdk-devel
  notify: restart tomcat9
  tags: zypper

- name: Copy tomcat9.repo
  template: src=tomcat9.repo.j2 dest=/etc/zypp/repos.d/SharedHosting.repo backup=yes
  tags: zypper

- name: Install tomcat9 RPMs
  zypper: name={{item}} state=present
  with_items:
    - ctomcat9
  tags: zypper

- name: Create {{base_dir}}/tomcat9 directory
  file: path={{base_dir}}/tomcat9 state=directory owner=tomcat group=root mode=0755

- name: Create {{base_dir}}/logs/tomcat9 directory
  file: path={{base_dir}}/logs/tomcat9 state=directory owner=tomcat group=tomcat mode=0755

- name: Add default files on {{base_dir}}/tomcat9/conf directory
  command: cp -r {{base_dir}}/tomcat9/install/conf {{base_dir}}/tomcat9/

- name: Set owner on conf Directory
  command: chown -R tomcat:tomcat {{base_dir}}/tomcat9/conf

- name: Create {{base_dir}}/tomcat9/logs symlink
  file: src={{base_dir}}/logs/tomcat9 dest={{base_dir}}/tomcat9/logs state=link

- name: Create {{base_dir}}/tomcat9/temp directory
  file: path={{base_dir}}/tomcat9/temp state=directory owner=tomcat group=tomcat mode=0775

- name: Create {{base_dir}}/tomcat9/webapps directory
  file: path={{base_dir}}/tomcat9/webapps state=directory owner=tomcat group=tomcat mode=0775

- name: Create {{base_dir}}/tomcat9/work directory
  file: path={{base_dir}}/tomcat9/work state=directory owner=tomcat group=tomcat mode=0775

- name: Configure {{base_dir}}/tomcat9/conf/server.xml
  template: src=server.xml.j2 dest={{base_dir}}/tomcat9/conf/server.xml backup=yes
  notify: restart tomcat9

- name: Configure {{base_dir}}/tomcat9/conf/logging.properties
  template: src=logging.properties.j2 dest={{base_dir}}/tomcat9/conf/logging.properties backup=yes
  notify: restart tomcat9

- name: Configure /etc/sysconfig/tomcat9
  template: src=sysconfig-tomcat9.j2 dest=/etc/sysconfig/tomcat9 backup=yes
  notify: restart tomcat9

- name: Copy statup unit script
  template: src=templates/tomcat9.service.j2 dest=/usr/lib/systemd/system/tomcat9.service owner=root group=root mode="0644" force=no
  notify: restart tomcat9

- name: Configure /etc/logrotate.d/tomcat9
  template: src=logrotate-tomcat9.j2 dest=/etc/logrotate.d/tomcat9
  notify: restart tomcat9

# ----------- START: SSL section
- name: Create {{base_dir}}/tomcat9/security directory
  file: path={{base_dir}}/tomcat9/security state=directory owner=tomcat group=tomcat

- name: Copy {{base_dir}}/tomcat9/security/keystore.jks
  copy: src=keystore.jks dest={{base_dir}}/tomcat9/security/keystore.jks force=no owner=tomcat group=tomcat
  notify: restart tomcat9

#- name: Copy /etc/pki/java/hpca2ssG2_ns.crt
#  copy: src=hpca2ssG2_ns.crt dest=/etc/pki/java/hpca2ssG2_ns.crt force=no

#- name: Import hpca2ssG2_ns.crt into /etc/pki/java/cacerts
#  command: /usr/bin/keytool -import -alias hpca2 -noprompt -trustcacerts -file /etc/pki/java/hpca2ssG2_ns.crt -storepass changeit -keystore /etc/pki/java/cacerts
#  ignore_errors: yes
#  changed_when: False

#- name: Copy /etc/pki/java/hpca2_recertified_ns.crt
#  copy: src=hpca2_recertified_ns.crt dest=/etc/pki/java/hpca2_recertified_ns.crt force=no

#- name: Import hpca2_recertified_ns.crt into /etc/pki/java/cacerts
#  command: /usr/bin/keytool -import -alias hpca2_rec -noprompt -trustcacerts -file /etc/pki/java/hpca2_recertified_ns.crt -storepass changeit -keystore /etc/pki/java/cacerts
#  ignore_errors: yes
#  changed_when: False
# ----------- END: SSL section

# ----------- START: ROOT welcome webapp section
# Creating each directory and file like this (for exploded deploy) turned out to be simpler than the current workarounds available for recursive copying.
- name: Create {{base_dir}}/tomcat9/webapps/ROOT directory
  file: path={{base_dir}}/tomcat9/webapps/ROOT state=directory owner=tomcat group=tomcat mode=0755

- name: Create {{base_dir}}/tomcat9/webapps/ROOT/WEB-INF directory
  file: path={{base_dir}}/tomcat9/webapps/ROOT/WEB-INF state=directory owner=tomcat group=tomcat mode=0755

- name: Create {{base_dir}}/tomcat9/webapps/ROOT/META-INF directory
  file: path={{base_dir}}/tomcat9/webapps/ROOT/META-INF state=directory owner=tomcat group=tomcat mode=0755

- name: Copy {{base_dir}}/tomcat9/webapps/ROOT/WEB-INF/web.xml
  copy: src=webapps/ROOT/WEB-INF/web.xml dest={{base_dir}}/tomcat9/webapps/ROOT/WEB-INF/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9

- name: Copy {{base_dir}}/tomcat9/webapps/ROOT/META-INF/MANIFEST.MF
  copy: src=webapps/ROOT/META-INF/MANIFEST.MF dest={{base_dir}}/tomcat9/webapps/ROOT/META-INF/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9

- name: Copy {{base_dir}}/tomcat9/webapps/ROOT/ROOT/index.jsp
  copy: src=webapps/ROOT/index.jsp dest={{base_dir}}/tomcat9/webapps/ROOT/index.jsp owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9
# ----------- END: ROOT welcome webapp section

# ----------- START: DO_NOT_REMOVE health check webapp section
# Creating each directory and file like this (for exploded deploy) turned out to be simpler than the current workarounds available for recursive copying.
- name: Create {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE directory
  file: path={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE state=directory owner=tomcat group=tomcat mode=0755

- name: Create {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/WEB-INF directory
  file: path={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/WEB-INF state=directory owner=tomcat group=tomcat mode=0755

- name: Create {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/META-INF directory
  file: path={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/META-INF state=directory owner=tomcat group=tomcat mode=0755

- name: Copy {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/WEB-INF/web.xml
  copy: src=webapps/DO_NOT_REMOVE/WEB-INF/web.xml dest={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/WEB-INF/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9

- name: Copy {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/META-INF/MANIFEST.MF
  copy: src=webapps/DO_NOT_REMOVE/META-INF/MANIFEST.MF dest={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/META-INF/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9

- name: Copy {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/health_check.jsp
  copy: src=webapps/DO_NOT_REMOVE/health_check.jsp dest={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9

- name: Copy {{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/health_check.html
  copy: src=webapps/DO_NOT_REMOVE/health_check.html dest={{base_dir}}/tomcat9/webapps/DO_NOT_REMOVE/ owner=tomcat group=tomcat mode=0644 force=no
  notify: restart tomcat9
# ----------- END: DO_NOT_REMOVE health check webapp section

# ----------- START: Tomcat Manager section
- name: Copy webapps/manager
  command: cp -r {{base_dir}}/tomcat9/install/webapps/manager {{base_dir}}/tomcat9/webapps
  notify: restart tomcat9

- name: Copy webapps/manager
  command: chown -R tomcat:tomcat {{base_dir}}/tomcat9/webapps/manager
  notify: restart tomcat9

#- name: Copy {{base_dir}}/tomcat9/webapps/manager/WEB-INF/web.xml
#  copy: src=web.xml dest={{base_dir}}/tomcat9/webapps/manager/WEB-INF/web.xml
#  notify: restart tomcat9
# ----------- END: Tomcat Manager section

- name: Add tomcat9 as service
  command: chkconfig tomcat9 on

- name: Ensure tomcat9 is running (and enable to autostart)
  service: name=tomcat9 enabled=yes state=started

- name: Configure /etc/monit.d/tomcat9 file
  template: src=monit-tomcat9.j2 dest=/etc/monit.d/tomcat9
  notify: restart monit

#- name: Configure motd
#  template: src=motd.j2 dest=/etc/motd
