---
    - name: restart jboss
      action: service name=jboss-eap state=restarted

    - name: stop jboss
      action: service name=jboss-eap state=stopped

    - name: start jboss
      action: service name=jboss-eap state=started

