---
- name: Copy SharedHosting.repo
  yum: name=DXC-SharedHosting-yum-repo state=latest
  tags: yum

#- name: Install SharedHosting repo
#  yum: name=hpit-yum-dash-repo state=latest
#  tags: yum

- name: Install Monit
  yum: name=hpit-monit state=latest
  tags: yum

- name: Configure /etc/monitrc file
  template: src=monitrc.j2 dest=/etc/monitrc
  notify: restart monit

- name: Ensure Monit is running (and enable to autostart)
  action: service name=monit enabled=yes state=started
