---
- name: Copy tomcat8.repo
  template: src=templates/tomcat8.repo.j2 dest=/etc/zypp/repos.d/SharedHosting.repo backup=yes
  tags: zypper

- name: Install Monit
  zypper: name=monit state=latest
  tags: zypper

- name: Configure /etc/monitrc file
  template: src=templates/monitrc.j2 dest=/etc/monitrc
  notify: restart monit

- name: Ensure Monit is running (and enable to autostart)
  action: service name=monit enabled=yes state=started
