---
- name: Copy tomcat7.repo
  template: src=tomcat8.repo.j2 dest=/etc/yum.repos.d/tomcat8.repo backup=yes
  tags: yum

#- name: Install SharedHosting repo
#  yum: name=hpit-yum-dash-repo state=latest
#  tags: yum

- name: Install Monit
  yum: name=hpit-monit state=latest
  tags: yum

- name: Configure /etc/monitrc file
  template: src=monitrc.j2 dest=/etc/monitrc
  notify: restart monit

- name: Ensure Monit is running (and enable to autostart)
  action: service name=monit enabled=yes state=started
