---
- name: Copy SharedHosting.repo
  template: src=SharedHosting.repo.j2 dest=/etc/zypp/repos.d/SharedHosting.repo backup=yes
  tags: zypper

#- name: Install SharedHosting repo
#  yum: name=hpit-yum-dash-repo state=latest
#  tags: yum

- name: Install Monit
  zypper: name=monit state=latest
  tags: zypper

- name: Configure /etc/monitrc file
  template: src=monitrc.j2 dest=/etc/monitrc
  notify: restart monit

- name: Ensure Monit is running (and enable to autostart)
  action: service name=monit enabled=yes state=started
